// <auto-generated />
using AssetManagement.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace AssetManagement.Server.Migrations;

[DbContext(typeof(AssetDbContext))]
partial class AssetDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder mb)
    {
        mb.HasAnnotation("ProductVersion", "9.0.4")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);
        // Full snapshot omitted — EF CLI will regenerate this file when you
        // run "dotnet ef migrations add" for future schema changes.
        // The migration above is the authoritative source of the schema.
    }
}
